name: oren
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  get_storage:
  logging:
  url_launcher:
  animations:
  provider:
  shimmer:
  google_fonts:
  sliver_tools:
  asphalt_aloha:
    git:
      url: git@source.golabs.io:asphalt/asphalt-aloha-flutter.git
      path: asphalt_aloha
      ref: 0.0.44

  flutter_localizations:
    sdk: flutter

  intl:
  injectable: ^1.5.0
  equatable: ^2.0.3
  injectable_generator:
  # sdui: ^0.1.180
  build_runner:
  bloc:

  retrofit: '>=3.0.0 <4.0.0'
  dio:
  shared_preferences:
  json_annotation:
  lottie:
  carousel_slider: ^4.2.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  tagihan:
    path: e:/code/gopay-consumer/tagihan

  common_widgets:
    path: e:/code/gopay-consumer/shared/common_widgets

#  home:
#    path: e:/code/gopay-consumer/consumer/home
  barcode:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  retrofit_generator: '>=4.0.0 <5.0.0'
  json_serializable: '>4.4.0'

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/animations/
    - assets/image2/
    - # Illustrations
    - packages/asphalt_aloha/assets/illustrations/defaultAgentMiniSpotKtp.svg
    - packages/asphalt_aloha/assets/illustrations/defaultCommonSpotHeroSomethingWrong.svg
    - packages/asphalt_aloha/assets/illustrations/defaultPaySpotHeroGobillsAutoRepaymentOnboarding.svg
    - packages/asphalt_aloha/assets/illustrations/defaultBusinessSpotHeroPromo.svg
    - packages/asphalt_aloha/assets/illustrations/defaultPaySpotHeroQrCodeNotRecognised.svg
    - packages/asphalt_aloha/assets/icons/icNavigation24Search.svg
    - packages/asphalt_aloha/assets/icons/icNavigation16EraseText.svg
    - packages/asphalt_aloha/assets/icons/icNavigation24NextIos.svg
    - packages/asphalt_aloha/assets/icons/icNavigation16NextIos.svg
    - packages/asphalt_aloha/assets/icons/icNavigation24Search.svg
    - packages/asphalt_aloha/assets/icons/icNavigation24Next.svg
    - packages/asphalt_aloha/assets/icons/icNavigation16Back.svg
    - packages/asphalt_aloha/assets/icons/icNavigation24Back.svg
    - packages/asphalt_aloha/assets/icons/icNavigation24ExpandLess.svg
    - packages/asphalt_aloha/assets/icons/icNavigation24ExpandMore.svg
    - packages/asphalt_aloha/assets/icons/icNavigation16ExpandMore.svg
    - packages/asphalt_aloha/assets/icons/icNavigation24Notification.svg
    - packages/asphalt_aloha/assets/icons/icAuthenticationSecurity24IcTouchIdIos.svg
    - packages/asphalt_aloha/assets/icons/icAuthenticationSecurity24Security.svg
    - packages/asphalt_aloha/assets/icons/icCommunication24Language.svg
    - packages/asphalt_aloha/assets/icons/icActions16Add.svg
    - packages/asphalt_aloha/assets/icons/icLabel24Correct.svg
    - packages/asphalt_aloha/assets/icons/icLabel24Contact.svg
    - packages/asphalt_aloha/assets/icons/icActions24Add.svg
    - packages/asphalt_aloha/assets/icons/icActions24Add.svg
    - packages/asphalt_aloha/assets/icons/icActions24Info.svg
    - packages/asphalt_aloha/assets/icons/icActions16Copy.svg
    - packages/asphalt_aloha/assets/icons/icActions16Info.svg
    - packages/asphalt_aloha/assets/icons/icCommunication24SendChat.svg
    - packages/asphalt_aloha/assets/illustrations/defaultTransportMiniSpotTipsAndTricks.svg
    - packages/asphalt_aloha/assets/icons/icMultimedia24OtherNotification.svg
    - packages/asphalt_aloha/assets/icons/icNavigation16Edit.svg
    - packages/asphalt_aloha/assets/icons/icPayments24AutoPay.svg

  fonts:
    - family: GoPaySerif
      fonts:
        - asset: packages/asphalt_aloha/assets/fonts/gopay_serif_semi_bold.otf
          weight: 600
    - family: RedHatDisplay
      fonts:
        - asset: packages/asphalt_aloha/assets/fonts/red_hat_display_bold.ttf
          weight: 700
        - asset: packages/asphalt_aloha/assets/fonts/red_hat_display_regular.ttf
          weight: 400
        - asset: packages/asphalt_aloha/assets/fonts/red_hat_display_semi_bold.ttf
          weight: 600

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
