name: oren
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  get_storage:
  logging:
  url_launcher:
  animations:
  provider:
  shimmer:

  flutter_localizations:
    sdk: flutter

  intl:
  injectable: ^1.5.0
  equatable: ^2.0.3
  injectable_generator:
  # sdui: ^0.1.180
  build_runner:
  bloc:

  retrofit: '>=3.0.0 <4.0.0'
  dio:
  shared_preferences:
  json_annotation:
  lottie:
  carousel_slider: ^4.2.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  retrofit_generator: '>=4.0.0 <5.0.0'
  json_serializable: '>4.4.0'

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/animations/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
